export const RESPONSE_USER_GITHUB = {
    incomplete_results: false,
    items: [
      {
        login: "esaputra",
        id: 3845034,
        node_id: "MDQ6VXNlcjM4NDUwMzQ=",
        avatar_url: "https://avatars.githubusercontent.com/u/3845034?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/esaputra",
        html_url: "https://github.com/esaputra",
        followers_url: "https://api.github.com/users/esaputra/followers",
        following_url : "https://api.github.com/users/esaputra/following{/other_user}",
        gists_url: "https://api.github.com/users/esaputra/gists{/gist_id}",
        starred_url: "https://api.github.com/users/esaputra/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/esaputra/subscriptions",
        organizations_url: "https://api.github.com/users/esaputra/orgs",
        repos_url: "https://api.github.com/users/esaputra/repos",
        events_url : "https://api.github.com/users/esaputra/events{/privacy}",
        received_events_url: "https://api.github.com/users/esaputra/received_events",
        type: "User",
        site_admin: false,
        score: 1
      }
    ],
    total_count:1
};

export const RESPONSE_REPOSSITORI_GITHUB = [{
    id: 467172418,
    node_id: "R_kgDOG9h8Qg",
    name: "express-js-api-starter",
    full_name: "esaputra95/express-js-api-starter",
    private: false,
    html_url: "https://github.com/esaputra95/express-js-api-starter",
    description: null,
    fork: false,
    url: "https://api.github.com/repos/esaputra95/express-js-api-starter",
    forks_url: "https://api.github.com/repos/esaputra95/express-js-api-starter/forks",
    keys_url: "https://api.github.com/repos/esaputra95/express-js-api-starter/keys{/key_id}",
    collaborators_url: "https://api.github.com/repos/esaputra95/express-js-api-starter/collaborators{/collaborator}",
    teams_url: "https://api.github.com/repos/esaputra95/express-js-api-starter/teams",
    hooks_url: "https://api.github.com/repos/esaputra95/express-js-api-starter/hooks",
    issue_events_url: "https://api.github.com/repos/esaputra95/express-js-api-starter/issues/events{/number}",
    events_url: "https://api.github.com/repos/esaputra95/express-js-api-starter/events",
    assignees_url: "https://api.github.com/repos/esaputra95/express-js-api-starter/assignees{/user}",
    branches_url: "https://api.github.com/repos/esaputra95/express-js-api-starter/branches{/branch}",
    tags_url: "https://api.github.com/repos/esaputra95/express-js-api-starter/tags",
    blobs_url: "https://api.github.com/repos/esaputra95/express-js-api-starter/git/blobs{/sha}",
    git_tags_url: "https://api.github.com/repos/esaputra95/express-js-api-starter/git/tags{/sha}",
    git_refs_url: "https://api.github.com/repos/esaputra95/express-js-api-starter/git/refs{/sha}",
    trees_url: "https://api.github.com/repos/esaputra95/express-js-api-starter/git/trees{/sha}",
    statuses_url: "https://api.github.com/repos/esaputra95/express-js-api-starter/statuses/{sha}",
    languages_url: "https://api.github.com/repos/esaputra95/express-js-api-starter/languages",
    stargazers_url: "https://api.github.com/repos/esaputra95/express-js-api-starter/stargazers",
    contributors_url: "https://api.github.com/repos/esaputra95/express-js-api-starter/contributors",
    subscribers_url: "https://api.github.com/repos/esaputra95/express-js-api-starter/subscribers",
    subscription_url: "https://api.github.com/repos/esaputra95/express-js-api-starter/subscription",
    commits_url: "https://api.github.com/repos/esaputra95/express-js-api-starter/commits{/sha}",
    git_commits_url: "https://api.github.com/repos/esaputra95/express-js-api-starter/git/commits{/sha}",
    comments_url: "https://api.github.com/repos/esaputra95/express-js-api-starter/comments{/number}",
    issue_comment_url: "https://api.github.com/repos/esaputra95/express-js-api-starter/issues/comments{/number}",
    contents_url: "https://api.github.com/repos/esaputra95/express-js-api-starter/contents/{+path}",
    compare_url: "https://api.github.com/repos/esaputra95/express-js-api-starter/compare/{base}...{head}",
    merges_url: "https://api.github.com/repos/esaputra95/express-js-api-starter/merges",
    archive_url: "https://api.github.com/repos/esaputra95/express-js-api-starter/{archive_format}{/ref}",
    downloads_url: "https://api.github.com/repos/esaputra95/express-js-api-starter/downloads",
    issues_url: "https://api.github.com/repos/esaputra95/express-js-api-starter/issues{/number}",
    pulls_url: "https://api.github.com/repos/esaputra95/express-js-api-starter/pulls{/number}",
    milestones_url: "https://api.github.com/repos/esaputra95/express-js-api-starter/milestones{/number}",
    notifications_url: "https://api.github.com/repos/esaputra95/express-js-api-starter/notifications{?since,all,participating}",
    labels_url: "https://api.github.com/repos/esaputra95/express-js-api-starter/labels{/name}",
    releases_url: "https://api.github.com/repos/esaputra95/express-js-api-starter/releases{/id}",
    deployments_url: "https://api.github.com/repos/esaputra95/express-js-api-starter/deployments",
    created_at: "2022-03-07T16:27:20Z",
    updated_at: "2022-03-07T16:39:49Z",
    pushed_at: "2023-03-03T12:30:02Z",
    git_url: "git://github.com/esaputra95/express-js-api-starter.git",
    ssh_url: "git@github.com:esaputra95/express-js-api-starter.git",
    clone_url: "https://github.com/esaputra95/express-js-api-starter.git",
    svn_url: "https://github.com/esaputra95/express-js-api-starter",
    homepage: null,
    size: 6514,
    stargazers_count: 0,
    watchers_count: 0,
    language: "JavaScript",
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    has_discussions: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: null,
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    topics: [],
    visibility: "public",
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: "master"

}]